name: "awscli2"
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: uname -a
    - run: nix --version
    - run: nix-build  --pure -E "with import <nixpkgs> {}; callPackage $PWD/default.nix {}"
